# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-08 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpayment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.CharField(default='Nikolai', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.CharField(default='Pushkin', max_length=40),
            preserve_default=False,
        ),
    ]
