# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-09 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpayment', '0005_auto_20200609_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='processing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
