# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-09 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userpayment', '0006_auto_20200609_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer', to='userpayment.Profile'),
        ),
    ]
