# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-10 09:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpayment', '0007_auto_20200609_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='sum',
            field=models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='payout',
            name='sum',
            field=models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
